<?php

$sqlupgrade = array();

// <Text String>, <DB Version Introduced>, <Query String>

$sqlupgrade[] = array('Clear Version Table', CODE_VER,
	"DELETE FROM `_version`;");


$sqlupgrade[] = array('Add ranked column to servers table', '1.11.0',
	"ALTER TABLE servers ADD ranked TINYINT DEFAULT 0 NOT NULL;");
	
$sqlupgrade[] = array('Add publicaddress column to servers table', '1.11.0',
	"ALTER TABLE servers ADD `publicaddress` varchar(100) CHARACTER SET utf8 NOT NULL DEFAULT '';");


$sqlupgrade[] = array('Add missing columns to stats_v table', '1.11.0',
	"ALTER TABLE stats_v
    ADD COLUMN `vdstry-14` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vdstry-15` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vdths-14` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vdths-15` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vkdr-14` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vkdr-15` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vkls-14` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vkls-15` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vrkls-14` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vrkls-15` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vtp-14` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `vtp-15` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `vbf-14` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vbf-15` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vbh-14` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vbh-15` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vaccu-14` int(11) unsigned NOT NULL DEFAULT '0',
    ADD COLUMN `vaccu-15` int(11) unsigned NOT NULL DEFAULT '0';");


$sqlupgrade[] = array('Add missing columns to stats_w table', '1.11.0',
	"ALTER TABLE stats_w
    ADD COLUMN `waccu-43` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `waccu-44` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `waccu-45` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `waccu-46` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `waccu-47` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `waccu-48` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wdths-43` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wdths-44` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wdths-45` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wdths-46` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wdths-47` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wdths-48` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `whts-43` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `whts-44` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `whts-45` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `whts-46` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `whts-47` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `whts-48` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wkdr-43` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wkdr-44` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wkdr-45` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wkdr-46` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wkdr-47` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wkdr-48` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wkls-43` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wkls-44` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wkls-45` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wkls-46` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wkls-47` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wkls-48` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wshts-43` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wshts-44` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wshts-45` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wshts-46` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wshts-47` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wshts-48` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtp-43` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtp-44` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtp-45` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtp-46` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtp-47` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtp-48` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtpk-43` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtpk-44` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtpk-45` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtpk-46` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtpk-47` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wtpk-48` varchar(20) NOT NULL DEFAULT '0',
    ADD COLUMN `wbf-43` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wbf-44` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wbf-45` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wbf-46` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wbf-47` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wbf-48` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wbh-43` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wbh-44` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wbh-45` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wbh-46` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wbh-47` int(11) NOT NULL DEFAULT '0',
    ADD COLUMN `wbh-48` int(11) NOT NULL DEFAULT '0';");


	
$sqlupgrade[] = array('Add country and ip columns to subaccount table', '1.11.0',
	"ALTER TABLE subaccount
    ADD COLUMN `country` varchar(2) DEFAULT 'xx',
	ADD COLUMN `ip` varchar(15) DEFAULT '';");




$sqlupgrade[] = array('Create new table dogtag_events', '1.11.0',
"CREATE TABLE IF NOT EXISTS `dogtag_events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `killer_id` int(10) unsigned NOT NULL,
  `victim_id` int(10) unsigned NOT NULL,
  `cnt` int(10) unsigned NOT NULL DEFAULT '0',
  `timestamp` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gm` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'game mode',
  `mapid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'map id',
  PRIMARY KEY (`id`),
  KEY `killer_id` (`killer_id`,`victim_id`,`timestamp`,`mapid`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;");




$sqlupgrade[] = array('Create new table ip2nation', '1.11.0',
"CREATE TABLE IF NOT EXISTS `ip2nation` (
  `ip` int(11) unsigned NOT NULL DEFAULT '0',
  `country` char(2) NOT NULL DEFAULT '',
  PRIMARY KEY (`ip`),
  KEY `ip` (`ip`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;");



$sqlupgrade[] = array('Create new table round_history', '1.11.0',
"CREATE TABLE IF NOT EXISTS `round_history` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
  `mapid` int(8) unsigned NOT NULL DEFAULT '0',
  `time` int(10) unsigned NOT NULL DEFAULT '0',
  `team1` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `team2` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `tickets1` int(10) unsigned NOT NULL DEFAULT '0',
  `tickets2` int(10) unsigned NOT NULL DEFAULT '0',
  `pids1` int(10) unsigned NOT NULL DEFAULT '0',
  `pids1_end` int(10) unsigned NOT NULL DEFAULT '0',
  `pids2` int(10) unsigned NOT NULL DEFAULT '0',
  `pids2_end` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `timestamp` (`timestamp`),
  KEY `mapid` (`mapid`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;");


$sqlupgrade[] = array('Create new maps view', '1.11.0',
"CREATE OR REPLACE
algorithm = UNDEFINED view `maps` as
select
    `stats_m`.`pid` as `id`,
    `stats_m`.`mapid` as `mapid`,
    max(`stats_m`.`mbr`) as `best`,
    max(0) as `worst`,
    sum(`stats_m`.`mwin`) as `win`,
    sum(`stats_m`.`mlos`) as `loss`,
    sum(`stats_m`.`mtt`) as `time`
from
    `stats_m`
group by
    `stats_m`.`pid`,
    `stats_m`.`mapid`;");


$sqlupgrade[] = array('Create new player view', '1.11.0',
"CREATE OR REPLACE
algorithm = UNDEFINED view `player` as
select
    `pp`.`pid` as `id`,
    `pp`.`rnk` as `rank`,
    `sa`.`country` as `country`,
    `pp`.`nick` as `name`,
    `pp`.`tt` as `time`,
    `pp`.`spm` as `spm`,
    `pp`.`kdr` as `kdr`,
    `pp`.`resp` as `ammos`,
    `pp`.`unavl` as `availunlocks`,
    `pp`.`ban` as `banned`,
    `pp`.`capa` as `captureassists`,
    `pp`.`captures` as `captures`,
    '0' as `chng`,
    '' as `clantag`,
    `pp`.`cs` as `cmdscore`,
    `pp`.`tac` as `cmdtime`,
    `pp`.`klla` as `damageassists`,
    `pp`.`dths` as `deaths`,
    `pp`.`dstrk` as `deathstreak`,
    '0' as `decr`,
    `pp`.`dcpt` as `defends`,
    `pp`.`dass` as `driverassists`,
    '0' as `driverspecials`,
    `pp`.`hls` as `heals`,
    '0' as `hidden`,
    `sa`.`ip` as `ip`,
    '0' as `isbot`,
    '0' as `joined`,
    `pp`.`kick` as `kicked`,
    `pp`.`klls` as `kills`,
    `pp`.`klstrk` as `killstreak`,
    '0' as `lastonline`,
    `pp`.`los` as `losses`,
    `pp`.`talw` as `lwtime`,
    '0' as `mode0`,
    '0' as `mode1`,
    '0' as `mode2`,
    '0' as `neutralizeassits`,
    `pp`.`ncpt` as `neutralizes`,
    '0' as `passengerassists`,
    '0' as `permban`,
    `pp`.`rps` as `repairs`,
    `pp`.`rvs` as `revives`,
    `pp`.`brs` as `rndscore`,
    (
    select
        sum((`sm`.`mwin` + `sm`.`mlos`))
    from
        `stats_m` `sm`
    where
        (`sm`.`pid` = `pp`.`pid`)) as `rounds`,
    `pp`.`gsco` as `score`,
    '0' as `skillscore`,
    `pp`.`tasl` as `sqltime`,
    `pp`.`tasm` as `sqmtime`,
    `pp`.`suic` as `suicides`,
    '0' as `targetassists`,
    `pp`.`tdmg` as `teamdamage`,
    `pp`.`tkls` as `teamkills`,
    `pp`.`twsc` as `teamscore`,
    `pp`.`tvdmg` as `teamvehicledamage`,
    `pp`.`unlc` as `usedunlocks`,
    `pp`.`wins` as `wins`,
    `pp`.`fe` as `fe`,
    `pp`.`fgm` as `fgm`,
    `pp`.`fk` as `fk`,
    `pp`.`fm` as `fm`,
    `pp`.`fv` as `fv`,
    `pp`.`fw` as `fw`
from
    `playerprogress` `pp`
left join `subaccount` `sa` on
    (`pp`.`pid` = `sa`.`id`);");



$sqlupgrade[] = array('Create new kits view', '1.11.0',
"CREATE OR REPLACE
algorithm = UNDEFINED view `kits` as
select
    `p`.`pid` as `id`,
    `p`.`ktt-0` as `time0`,
    `p`.`kkls-0` as `kills0`,
    `p`.`kdths-0` as `deaths0`,
    `p`.`ktt-1` as `time1`,
    `p`.`kkls-1` as `kills1`,
    `p`.`kdths-1` as `deaths1`,
    `p`.`ktt-2` as `time2`,
    `p`.`kkls-2` as `kills2`,
    `p`.`kdths-2` as `deaths2`,
    `p`.`ktt-3` as `time3`,
    `p`.`kkls-3` as `kills3`,
    `p`.`kdths-3` as `deaths3`
from
    `playerprogress` `p`;");



$sqlupgrade[] = array('Create new weapons view', '1.11.0',
"CREATE OR REPLACE
algorithm = UNDEFINED view `weapons` as
select
    `sw`.`pid` as `id`,
    `sw`.`wtp-0` as `time0`,
    `sw`.`wkls-0` as `kills0`,
    `sw`.`wdths-0` as `deaths0`,
    `sw`.`wbf-0` as `fired0`,
    `sw`.`wbh-0` as `hit0`,
    `sw`.`wtp-1` as `time1`,
    `sw`.`wkls-1` as `kills1`,
    `sw`.`wdths-1` as `deaths1`,
    `sw`.`wbf-1` as `fired1`,
    `sw`.`wbh-1` as `hit1`,
    `sw`.`wtp-2` as `time2`,
    `sw`.`wkls-2` as `kills2`,
    `sw`.`wdths-2` as `deaths2`,
    `sw`.`wbf-2` as `fired2`,
    `sw`.`wbh-2` as `hit2`,
    `sw`.`wtp-3` as `time3`,
    `sw`.`wkls-3` as `kills3`,
    `sw`.`wdths-3` as `deaths3`,
    `sw`.`wbf-3` as `fired3`,
    `sw`.`wbh-3` as `hit3`,
    `sw`.`wtp-4` as `time4`,
    `sw`.`wkls-4` as `kills4`,
    `sw`.`wdths-4` as `deaths4`,
    `sw`.`wbf-4` as `fired4`,
    `sw`.`wbh-4` as `hit4`,
    `sw`.`wtp-5` as `time5`,
    `sw`.`wkls-5` as `kills5`,
    `sw`.`wdths-5` as `deaths5`,
    `sw`.`wbf-5` as `fired5`,
    `sw`.`wbh-5` as `hit5`,
    `sw`.`wtp-6` as `time6`,
    `sw`.`wkls-6` as `kills6`,
    `sw`.`wdths-6` as `deaths6`,
    `sw`.`wbf-6` as `fired6`,
    `sw`.`wbh-6` as `hit6`,
    `sw`.`wtp-7` as `time7`,
    `sw`.`wkls-7` as `kills7`,
    `sw`.`wdths-7` as `deaths7`,
    `sw`.`wbf-7` as `fired7`,
    `sw`.`wbh-7` as `hit7`,
    `sw`.`wtp-8` as `time8`,
    `sw`.`wkls-8` as `kills8`,
    `sw`.`wdths-8` as `deaths8`,
    `sw`.`wbf-8` as `fired8`,
    `sw`.`wbh-8` as `hit8`,
    `sw`.`wtp-9` as `time9`,
    `sw`.`wkls-9` as `kills9`,
    `sw`.`wdths-9` as `deaths9`,
    `sw`.`wbf-9` as `fired9`,
    `sw`.`wbh-9` as `hit9`,
    `sw`.`wtp-10` as `time10`,
    `sw`.`wkls-10` as `kills10`,
    `sw`.`wdths-10` as `deaths10`,
    `sw`.`wbf-10` as `fired10`,
    `sw`.`wbh-10` as `hit10`,
    `sw`.`wtp-11` as `time11`,
    `sw`.`wkls-11` as `kills11`,
    `sw`.`wdths-11` as `deaths11`,
    `sw`.`wbf-11` as `fired11`,
    `sw`.`wbh-11` as `hit11`,
    `sw`.`wtp-12` as `time12`,
    `sw`.`wkls-12` as `kills12`,
    `sw`.`wdths-12` as `deaths12`,
    `sw`.`wbf-12` as `fired12`,
    `sw`.`wbh-12` as `hit12`,
    `sw`.`wtp-13` as `time13`,
    `sw`.`wkls-13` as `kills13`,
    `sw`.`wdths-13` as `deaths13`,
    `sw`.`wbf-13` as `fired13`,
    `sw`.`wbh-13` as `hit13`,
    `sw`.`wtp-14` as `time14`,
    `sw`.`wkls-14` as `kills14`,
    `sw`.`wdths-14` as `deaths14`,
    `sw`.`wbf-14` as `fired14`,
    `sw`.`wbh-14` as `hit14`,
    `sw`.`wtp-15` as `time15`,
    `sw`.`wkls-15` as `kills15`,
    `sw`.`wdths-15` as `deaths15`,
    `sw`.`wbf-15` as `fired15`,
    `sw`.`wbh-15` as `hit15`,
    `sw`.`wtp-16` as `time16`,
    `sw`.`wkls-16` as `kills16`,
    `sw`.`wdths-16` as `deaths16`,
    `sw`.`wbf-16` as `fired16`,
    `sw`.`wbh-16` as `hit16`,
    `sw`.`wtp-17` as `time17`,
    `sw`.`wkls-17` as `kills17`,
    `sw`.`wdths-17` as `deaths17`,
    `sw`.`wbf-17` as `fired17`,
    `sw`.`wbh-17` as `hit17`,
    `sw`.`wtp-18` as `time18`,
    `sw`.`wkls-18` as `kills18`,
    `sw`.`wdths-18` as `deaths18`,
    `sw`.`wbf-18` as `fired18`,
    `sw`.`wbh-18` as `hit18`,
    `sw`.`wtp-19` as `time19`,
    `sw`.`wkls-19` as `kills19`,
    `sw`.`wdths-19` as `deaths19`,
    `sw`.`wbf-19` as `fired19`,
    `sw`.`wbh-19` as `hit19`,
    `sw`.`wtp-20` as `time20`,
    `sw`.`wkls-20` as `kills20`,
    `sw`.`wdths-20` as `deaths20`,
    `sw`.`wbf-20` as `fired20`,
    `sw`.`wbh-20` as `hit20`,
    `sw`.`wtp-21` as `time21`,
    `sw`.`wkls-21` as `kills21`,
    `sw`.`wdths-21` as `deaths21`,
    `sw`.`wbf-21` as `fired21`,
    `sw`.`wbh-21` as `hit21`,
    `sw`.`wtp-22` as `time22`,
    `sw`.`wkls-22` as `kills22`,
    `sw`.`wdths-22` as `deaths22`,
    `sw`.`wbf-22` as `fired22`,
    `sw`.`wbh-22` as `hit22`,
    `sw`.`wtp-23` as `time23`,
    `sw`.`wkls-23` as `kills23`,
    `sw`.`wdths-23` as `deaths23`,
    `sw`.`wbf-23` as `fired23`,
    `sw`.`wbh-23` as `hit23`,
    `sw`.`wtp-24` as `time24`,
    `sw`.`wkls-24` as `kills24`,
    `sw`.`wdths-24` as `deaths24`,
    `sw`.`wbf-24` as `fired24`,
    `sw`.`wbh-24` as `hit24`,
    `sw`.`wtp-25` as `time25`,
    `sw`.`wkls-25` as `kills25`,
    `sw`.`wdths-25` as `deaths25`,
    `sw`.`wbf-25` as `fired25`,
    `sw`.`wbh-25` as `hit25`,
    `sw`.`wtp-26` as `time26`,
    `sw`.`wkls-26` as `kills26`,
    `sw`.`wdths-26` as `deaths26`,
    `sw`.`wbf-26` as `fired26`,
    `sw`.`wbh-26` as `hit26`,
    `sw`.`wtp-27` as `time27`,
    `sw`.`wkls-27` as `kills27`,
    `sw`.`wdths-27` as `deaths27`,
    `sw`.`wbf-27` as `fired27`,
    `sw`.`wbh-27` as `hit27`,
    `sw`.`wtp-28` as `time28`,
    `sw`.`wkls-28` as `kills28`,
    `sw`.`wdths-28` as `deaths28`,
    `sw`.`wbf-28` as `fired28`,
    `sw`.`wbh-28` as `hit28`,
    `sw`.`wtp-29` as `time29`,
    `sw`.`wkls-29` as `kills29`,
    `sw`.`wdths-29` as `deaths29`,
    `sw`.`wbf-29` as `fired29`,
    `sw`.`wbh-29` as `hit29`,
    `sw`.`wtp-30` as `time30`,
    `sw`.`wkls-30` as `kills30`,
    `sw`.`wdths-30` as `deaths30`,
    `sw`.`wbf-30` as `fired30`,
    `sw`.`wbh-30` as `hit30`,
    `sw`.`wtp-31` as `time31`,
    `sw`.`wkls-31` as `kills31`,
    `sw`.`wdths-31` as `deaths31`,
    `sw`.`wbf-31` as `fired31`,
    `sw`.`wbh-31` as `hit31`,
    `sw`.`wtp-32` as `time32`,
    `sw`.`wkls-32` as `kills32`,
    `sw`.`wdths-32` as `deaths32`,
    `sw`.`wbf-32` as `fired32`,
    `sw`.`wbh-32` as `hit32`,
    `sw`.`wtp-33` as `time33`,
    `sw`.`wkls-33` as `kills33`,
    `sw`.`wdths-33` as `deaths33`,
    `sw`.`wbf-33` as `fired33`,
    `sw`.`wbh-33` as `hit33`,
    `sw`.`wtp-34` as `time34`,
    `sw`.`wkls-34` as `kills34`,
    `sw`.`wdths-34` as `deaths34`,
    `sw`.`wbf-34` as `fired34`,
    `sw`.`wbh-34` as `hit34`,
    `sw`.`wtp-35` as `time35`,
    `sw`.`wkls-35` as `kills35`,
    `sw`.`wdths-35` as `deaths35`,
    `sw`.`wbf-35` as `fired35`,
    `sw`.`wbh-35` as `hit35`,
    `sw`.`wtp-36` as `time36`,
    `sw`.`wkls-36` as `kills36`,
    `sw`.`wdths-36` as `deaths36`,
    `sw`.`wbf-36` as `fired36`,
    `sw`.`wbh-36` as `hit36`,
    `sw`.`wtp-37` as `time37`,
    `sw`.`wkls-37` as `kills37`,
    `sw`.`wdths-37` as `deaths37`,
    `sw`.`wbf-37` as `fired37`,
    `sw`.`wbh-37` as `hit37`,
    `sw`.`wtp-38` as `time38`,
    `sw`.`wkls-38` as `kills38`,
    `sw`.`wdths-38` as `deaths38`,
    `sw`.`wbf-38` as `fired38`,
    `sw`.`wbh-38` as `hit38`,
    `sw`.`wtp-39` as `time39`,
    `sw`.`wkls-39` as `kills39`,
    `sw`.`wdths-39` as `deaths39`,
    `sw`.`wbf-39` as `fired39`,
    `sw`.`wbh-39` as `hit39`,
    `sw`.`wtp-40` as `time40`,
    `sw`.`wkls-40` as `kills40`,
    `sw`.`wdths-40` as `deaths40`,
    `sw`.`wbf-40` as `fired40`,
    `sw`.`wbh-40` as `hit40`,
    `sw`.`wtp-41` as `time41`,
    `sw`.`wkls-41` as `kills41`,
    `sw`.`wdths-41` as `deaths41`,
    `sw`.`wbf-41` as `fired41`,
    `sw`.`wbh-41` as `hit41`,
    `sw`.`wtp-42` as `time42`,
    `sw`.`wkls-42` as `kills42`,
    `sw`.`wdths-42` as `deaths42`,
    `sw`.`wbf-42` as `fired42`,
    `sw`.`wbh-42` as `hit42`,
    `sw`.`wtp-43` as `time43`,
    `sw`.`wkls-43` as `kills43`,
    `sw`.`wdths-43` as `deaths43`,
    `sw`.`wbf-43` as `fired43`,
    `sw`.`wbh-43` as `hit43`,
    `sw`.`wtp-44` as `time44`,
    `sw`.`wkls-44` as `kills44`,
    `sw`.`wdths-44` as `deaths44`,
    `sw`.`wbf-44` as `fired44`,
    `sw`.`wbh-44` as `hit44`,
    `sw`.`wtp-45` as `time45`,
    `sw`.`wkls-45` as `kills45`,
    `sw`.`wdths-45` as `deaths45`,
    `sw`.`wbf-45` as `fired45`,
    `sw`.`wbh-45` as `hit45`,
    `sw`.`wtp-46` as `time46`,
    `sw`.`wkls-46` as `kills46`,
    `sw`.`wdths-46` as `deaths46`,
    `sw`.`wbf-46` as `fired46`,
    `sw`.`wbh-46` as `hit46`,
    `sw`.`wtp-47` as `time47`,
    `sw`.`wkls-47` as `kills47`,
    `sw`.`wdths-47` as `deaths47`,
    `sw`.`wbf-47` as `fired47`,
    `sw`.`wbh-47` as `hit47`
from
    `stats_w` `sw`;");


$sqlupgrade[] = array('Create new v_unlocks view', '1.11.0',
"CREATE OR REPLACE
algorithm = UNDEFINED view `v_unlocks` as
select
    `u`.`pid` as `id`,
    concat(`u`.`ukit`, concat(`u`.`utree`, `u`.`uorder`)) as `kit`,
    'y' as `state`
from
    `unlocks` `u`;");


$sqlupgrade[] = array('Create new vehicles view', '1.11.0',
"CREATE OR REPLACE
algorithm = UNDEFINED view `vehicles` as
select
    `sv`.`pid` as `id`,
    `sv`.`vdths-0` as `deaths0`,
    `sv`.`vtp-0` as `time0`,
    `sv`.`vkls-0` as `kills0`,
    `sv`.`vrkls-0` as `rk0`,
    `sv`.`vdths-1` as `deaths1`,
    `sv`.`vtp-1` as `time1`,
    `sv`.`vkls-1` as `kills1`,
    `sv`.`vrkls-1` as `rk1`,
    `sv`.`vdths-2` as `deaths2`,
    `sv`.`vtp-2` as `time2`,
    `sv`.`vkls-2` as `kills2`,
    `sv`.`vrkls-2` as `rk2`,
    `sv`.`vdths-4` as `deaths4`,
    `sv`.`vtp-4` as `time4`,
    `sv`.`vkls-4` as `kills4`,
    `sv`.`vrkls-4` as `rk4`,
    `sv`.`vdths-6` as `deaths6`,
    `sv`.`vtp-6` as `time6`,
    `sv`.`vkls-6` as `kills6`,
    `sv`.`vrkls-6` as `rk6`,
    `sv`.`vdths-7` as `deaths7`,
    `sv`.`vtp-7` as `time7`,
    `sv`.`vkls-7` as `kills7`,
    `sv`.`vrkls-7` as `rk7`,
    `sv`.`vdths-8` as `deaths8`,
    `sv`.`vtp-8` as `time8`,
    `sv`.`vkls-8` as `kills8`,
    `sv`.`vrkls-8` as `rk8`,
    `sv`.`vdths-10` as `deaths10`,
    `sv`.`vtp-10` as `time10`,
    `sv`.`vkls-10` as `kills10`,
    `sv`.`vrkls-10` as `rk10`,
    `sv`.`vdths-11` as `deaths11`,
    `sv`.`vtp-11` as `time11`,
    `sv`.`vkls-11` as `kills11`,
    `sv`.`vrkls-11` as `rk11`,
    `sv`.`vdths-12` as `deaths12`,
    `sv`.`vtp-12` as `time12`,
    `sv`.`vkls-12` as `kills12`,
    `sv`.`vrkls-12` as `rk12`,
    `sv`.`vdths-13` as `deaths13`,
    `sv`.`vtp-13` as `time13`,
    `sv`.`vkls-13` as `kills13`,
    `sv`.`vrkls-13` as `rk13`,
    `sv`.`vdths-14` as `deaths14`,
    `sv`.`vtp-14` as `time14`,
    `sv`.`vkls-14` as `kills14`,
    `sv`.`vrkls-14` as `rk14`,
    `sv`.`vdths-15` as `deaths15`,
    `sv`.`vtp-15` as `time15`,
    `sv`.`vkls-15` as `kills15`,
    `sv`.`vrkls-15` as `rk15`
from
    `stats_v` `sv`;");

    
$sqlupgrade[] = array('Create new table kills', '1.11.0',
"CREATE TABLE IF NOT EXISTS `kills` (
  `attacker` int(8) unsigned DEFAULT NULL,
  `victim` int(8) unsigned DEFAULT NULL,
  `count` int(10) unsigned DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;");



$sqlupgrade[] = array('Create new pivot pmaps view', '1.11.0',
"CREATE OR REPLACE
algorithm = UNDEFINED view `pmaps` as
select
    `p`.`pid` as `pid`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 0)) then `sm`.`mtt` end)) as `mtt-0-0`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 0)) then `sm`.`mwin` end)) as `mwin-0-0`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 1)) then `sm`.`mtt` end)) as `mtt-0-1`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 1)) then `sm`.`mwin` end)) as `mwin-0-1`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 2)) then `sm`.`mtt` end)) as `mtt-0-2`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 2)) then `sm`.`mwin` end)) as `mwin-0-2`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 3)) then `sm`.`mtt` end)) as `mtt-0-3`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 3)) then `sm`.`mwin` end)) as `mwin-0-3`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 4)) then `sm`.`mtt` end)) as `mtt-0-4`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 4)) then `sm`.`mwin` end)) as `mwin-0-4`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 5)) then `sm`.`mtt` end)) as `mtt-0-5`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 5)) then `sm`.`mwin` end)) as `mwin-0-5`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 6)) then `sm`.`mtt` end)) as `mtt-0-6`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 6)) then `sm`.`mwin` end)) as `mwin-0-6`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 7)) then `sm`.`mtt` end)) as `mtt-0-7`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 7)) then `sm`.`mwin` end)) as `mwin-0-7`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 8)) then `sm`.`mtt` end)) as `mtt-0-8`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 8)) then `sm`.`mwin` end)) as `mwin-0-8`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 9)) then `sm`.`mtt` end)) as `mtt-0-9`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 9)) then `sm`.`mwin` end)) as `mwin-0-9`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 0)) then `sm`.`mtt` end)) as `mtt-1-0`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 0)) then `sm`.`mwin` end)) as `mwin-1-0`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 1)) then `sm`.`mtt` end)) as `mtt-1-1`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 1)) then `sm`.`mwin` end)) as `mwin-1-1`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 2)) then `sm`.`mtt` end)) as `mtt-1-2`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 2)) then `sm`.`mwin` end)) as `mwin-1-2`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 3)) then `sm`.`mtt` end)) as `mtt-1-3`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 3)) then `sm`.`mwin` end)) as `mwin-1-3`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 4)) then `sm`.`mtt` end)) as `mtt-1-4`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 4)) then `sm`.`mwin` end)) as `mwin-1-4`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 5)) then `sm`.`mtt` end)) as `mtt-1-5`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 5)) then `sm`.`mwin` end)) as `mwin-1-5`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 6)) then `sm`.`mtt` end)) as `mtt-1-6`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 6)) then `sm`.`mwin` end)) as `mwin-1-6`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 7)) then `sm`.`mtt` end)) as `mtt-1-7`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 7)) then `sm`.`mwin` end)) as `mwin-1-7`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 8)) then `sm`.`mtt` end)) as `mtt-1-8`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 8)) then `sm`.`mwin` end)) as `mwin-1-8`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 9)) then `sm`.`mtt` end)) as `mtt-1-9`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 9)) then `sm`.`mwin` end)) as `mwin-1-9`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 10)) then `sm`.`mtt` end)) as `mtt-0-10`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 10)) then `sm`.`mwin` end)) as `mwin-0-10`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 11)) then `sm`.`mtt` end)) as `mtt-0-11`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 11)) then `sm`.`mwin` end)) as `mwin-0-11`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 12)) then `sm`.`mtt` end)) as `mtt-0-12`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 12)) then `sm`.`mwin` end)) as `mwin-0-12`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 10)) then `sm`.`mtt` end)) as `mtt-1-10`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 10)) then `sm`.`mwin` end)) as `mwin-1-10`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 11)) then `sm`.`mtt` end)) as `mtt-1-11`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 11)) then `sm`.`mwin` end)) as `mwin-1-11`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 12)) then `sm`.`mtt` end)) as `mtt-1-12`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 12)) then `sm`.`mwin` end)) as `mwin-1-12`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 10)) then `sm`.`mtt` end)) as `mtt-2-10`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 10)) then `sm`.`mwin` end)) as `mwin-2-10`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 11)) then `sm`.`mtt` end)) as `mtt-2-11`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 11)) then `sm`.`mwin` end)) as `mwin-2-11`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 12)) then `sm`.`mtt` end)) as `mtt-2-12`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 12)) then `sm`.`mwin` end)) as `mwin-2-12`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 14)) then `sm`.`mtt` end)) as `mtt-2-14`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 14)) then `sm`.`mwin` end)) as `mwin-2-14`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 0)) then `sm`.`mbr` end)) as `mbr-0-0`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 1)) then `sm`.`mbr` end)) as `mbr-0-1`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 2)) then `sm`.`mbr` end)) as `mbr-0-2`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 3)) then `sm`.`mbr` end)) as `mbr-0-3`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 4)) then `sm`.`mbr` end)) as `mbr-0-4`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 5)) then `sm`.`mbr` end)) as `mbr-0-5`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 6)) then `sm`.`mbr` end)) as `mbr-0-6`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 7)) then `sm`.`mbr` end)) as `mbr-0-7`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 8)) then `sm`.`mbr` end)) as `mbr-0-8`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 9)) then `sm`.`mbr` end)) as `mbr-0-9`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 0)) then `sm`.`mbr` end)) as `mbr-1-0`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 1)) then `sm`.`mbr` end)) as `mbr-1-1`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 2)) then `sm`.`mbr` end)) as `mbr-1-2`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 3)) then `sm`.`mbr` end)) as `mbr-1-3`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 4)) then `sm`.`mbr` end)) as `mbr-1-4`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 5)) then `sm`.`mbr` end)) as `mbr-1-5`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 6)) then `sm`.`mbr` end)) as `mbr-1-6`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 7)) then `sm`.`mbr` end)) as `mbr-1-7`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 8)) then `sm`.`mbr` end)) as `mbr-1-8`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 9)) then `sm`.`mbr` end)) as `mbr-1-9`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 10)) then `sm`.`mbr` end)) as `mbr-0-10`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 11)) then `sm`.`mbr` end)) as `mbr-0-11`,
    max((case when ((`sm`.`gm` in (0, 3)) and (`sm`.`mapid` = 12)) then `sm`.`mbr` end)) as `mbr-0-12`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 10)) then `sm`.`mbr` end)) as `mbr-1-10`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 11)) then `sm`.`mbr` end)) as `mbr-1-11`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 12)) then `sm`.`mbr` end)) as `mbr-1-12`,
    max((case when ((`sm`.`gm` = 1) and (`sm`.`mapid` = 14)) then `sm`.`mbr` end)) as `mbr-1-14`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 10)) then `sm`.`mbr` end)) as `mbr-2-10`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 11)) then `sm`.`mbr` end)) as `mbr-2-11`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 12)) then `sm`.`mbr` end)) as `mbr-2-12`,
    max((case when ((`sm`.`gm` = 2) and (`sm`.`mapid` = 14)) then `sm`.`mbr` end)) as `mbr-2-14`
from
    (`playerprogress` `p`
join `stats_m` `sm` on
    ((`sm`.`pid` = `p`.`pid`)))
group by
    `p`.`pid`;");


$sqlupgrade[] = array('Add comment to csgpm-0 in playerprogress', '1.11.1',
"ALTER TABLE bf2142stats_dev.playerprogress MODIFY COLUMN `csgpm-0` int(10) unsigned DEFAULT 0 NOT NULL COMMENT 'Conquest commander score';");

$sqlupgrade[] = array('Add comment to csgpm-0 in playerprogress', '1.11.1',
"INSERT INTO mapinfo (id, name, score, `time`, times, kills, deaths, custom) VALUES
(0, 'suez_canal', 0, 0, 0, 0, 0, 0),
(1, 'verdun', 0, 0, 0, 0, 0, 0),
(2, 'shuhia_taiba', 0, 0, 0, 0, 0, 0),
(3, 'minsk', 0, 0, 0, 0, 0, 0),
(4, 'camp_gibraltar', 0, 0, 0, 0, 0, 0),
(5, 'sidi_power_plant', 0, 0, 0, 0, 0, 0),
(6, 'fall_of_berlin', 0, 0, 0, 0, 0, 0),
(7, 'belgrade', 0, 0, 0, 0, 0, 0),
(8, 'cerbere_landing', 0, 0, 0, 0, 0, 0),
(9, 'tunis_harbor', 0, 0, 0, 0, 0, 0),
(10, 'bridge_at_remagen', 0, 0, 0, 0, 0, 0),
(11, 'liberation_of_leipzig', 0, 0, 0, 0, 0, 0),
(12, 'port_bavaria', 0, 0, 0, 0, 0, 0),
(14, 'highway_tampa', 0, 0, 0, 0, 0, 0),
(15, 'operation_blue_pearl', 0, 0, 0, 0, 0, 0),
(16, 'wake_island_2142', 0, 0, 0, 0, 0, 0),
(17, 'operation_shingle', 0, 0, 0, 0, 0, 0),
(18, 'yellow_knife', 0, 0, 0, 0, 0, 0),
(19, 'strike_at_karkand', 0, 0, 0, 0, 0, 0),
(20, 'molokai', 0, 0, 0, 0, 0, 0),
(101, 'sidi_power_plant_coop', 0, 0, 0, 0, 0, 0),
(102, 'hamburg_harbour_coop', 0, 0, 0, 0, 0, 0),
(103, 'verdun_coop', 0, 0, 0, 0, 0, 0),
(104, 'tunis_harbor_coop', 0, 0, 0, 0, 0, 0),
(105, 'suez_canal_coop', 0, 0, 0, 0, 0, 0),
(106, 'shuhia_taiba_coop', 0, 0, 0, 0, 0, 0),
(107, 'operation_shingle_coop', 0, 0, 0, 0, 0, 0),
(108, 'minsk_coop', 0, 0, 0, 0, 0, 0),
(109, 'liberation_of_leipzig_coop', 0, 0, 0, 0, 0, 0),
(110, 'highway_tampa_coop', 0, 0, 0, 0, 0, 0),
(111, 'cerbere_landing_coop', 0, 0, 0, 0, 0, 0),
(112, 'camp_gibraltar_coop', 0, 0, 0, 0, 0, 0),
(113, 'camp_gibraltar_2_coop', 0, 0, 0, 0, 0, 0),
(114, 'bridge_at_remagen_coop', 0, 0, 0, 0, 0, 0),
(115, 'belgrade_coop', 0, 0, 0, 0, 0, 0),
(116, 'fall_of_berlin_coop', 0, 0, 0, 0, 0, 0);
");

$sqlupgrade[] = array('Change global score to signed int', '1.11.1',
"ALTER TABLE playerprogress MODIFY COLUMN gsco int NOT NULL COMMENT 'general score';");

$sqlupgrade[] = array('Change score in mapinfo to bigint', '1.11.1',
"ALTER TABLE mapinfo MODIFY COLUMN score bigint DEFAULT 0 NOT NULL;");



$sqlupgrade[] = array('Fix joined and lastonline date for player stats', '1.11.2',
"CREATE OR REPLACE
algorithm = UNDEFINED view `player` as
select
    `pp`.`pid` as `id`,
    `pp`.`rnk` as `rank`,
    `sa`.`country` as `country`,
    `pp`.`nick` as `name`,
    `pp`.`tt` as `time`,
    `pp`.`spm` as `spm`,
    `pp`.`kdr` as `kdr`,
    `pp`.`resp` as `ammos`,
    `pp`.`unavl` as `availunlocks`,
    `pp`.`ban` as `banned`,
    `pp`.`capa` as `captureassists`,
    `pp`.`captures` as `captures`,
    '0' as `chng`,
    '' as `clantag`,
    `pp`.`cs` as `cmdscore`,
    `pp`.`tac` as `cmdtime`,
    `pp`.`klla` as `damageassists`,
    `pp`.`dths` as `deaths`,
    `pp`.`dstrk` as `deathstreak`,
    '0' as `decr`,
    `pp`.`dcpt` as `defends`,
    `pp`.`dass` as `driverassists`,
    '0' as `driverspecials`,
    `pp`.`hls` as `heals`,
    '0' as `hidden`,
    `sa`.`ip` as `ip`,
    '0' as `isbot`,
    `pp`.`acdt` as `joined`,
    `pp`.`kick` as `kicked`,
    `pp`.`klls` as `kills`,
    `pp`.`klstrk` as `killstreak`,
    `pp`.`lgdt` as `lastonline`,
    `pp`.`los` as `losses`,
    `pp`.`talw` as `lwtime`,
    '0' as `mode0`,
    '0' as `mode1`,
    '0' as `mode2`,
    '0' as `neutralizeassits`,
    `pp`.`ncpt` as `neutralizes`,
    '0' as `passengerassists`,
    '0' as `permban`,
    `pp`.`rps` as `repairs`,
    `pp`.`rvs` as `revives`,
    `pp`.`brs` as `rndscore`,
    (
    select
        sum((`sm`.`mwin` + `sm`.`mlos`))
    from
        `stats_m` `sm`
    where
        (`sm`.`pid` = `pp`.`pid`)) as `rounds`,
    `pp`.`gsco` as `score`,
    '0' as `skillscore`,
    `pp`.`tasl` as `sqltime`,
    `pp`.`tasm` as `sqmtime`,
    `pp`.`suic` as `suicides`,
    '0' as `targetassists`,
    `pp`.`tdmg` as `teamdamage`,
    `pp`.`tkls` as `teamkills`,
    `pp`.`twsc` as `teamscore`,
    `pp`.`tvdmg` as `teamvehicledamage`,
    `pp`.`unlc` as `usedunlocks`,
    `pp`.`wins` as `wins`,
    `pp`.`fe` as `fe`,
    `pp`.`fgm` as `fgm`,
    `pp`.`fk` as `fk`,
    `pp`.`fm` as `fm`,
    `pp`.`fv` as `fv`,
    `pp`.`fw` as `fw`
from
    (`playerprogress` `pp`
left join `subaccount` `sa` on
    ((`pp`.`pid` = `sa`.`id`)));");



$sqlupgrade[] = array('Update Version Table', CODE_VER,
	"INSERT INTO `_version` VALUES ('". CODE_VER ."', ".time().");");

?>